FundamentosPlay/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from Proyecto import settings
from .views import apiREST
from .views import home,teachers, question, administrator




urlpatterns = [

    path('', home.home, name='home'),
    path('admin/', admin.site.urls),
    path('profile/<str:username>/', home.view_profile, name='profile'),
    path('user/<int:user_pk>/rol/' ,home.edit_rol, name='edit_rol'),
    path('user/<str:user_username>/', home.edit_user_password, name='edit_user_password'),
    path('user/<int:user_pk>/delete/', home.user_delete, name='user_delete'),
    path('user/<int:user_pk>/active/', home.user_active, name='user_active'),
    path('email_confirm/<str:activation_key>/', home.email_confirm, name='email_confirm'),
    path('logout', home.logout, name='salir'),
    path('descarga', home.descarga, name='descarga'),
    path('leaderboard', home.leaderboard, name='leaderboard'),
    path('contactanos', home.sendMail, name='sendMail'),

   #__________________________________ URL PARA API REST _____________________________-
    path('api/', include(([
        #url de servicios
        path('medallas/<str:username>/', apiREST.Ficha.as_view()),
        path('nivel/<str:username>/', apiREST.Nivel.as_view()),
        path('leaderboard/', apiREST.LeaderBoard.as_view(), name='leaderboard'),
    ], 'FundamentosPlay'), namespace='api')),

   #______________________________  URLS PARA  ADMINISTRACIÓN ________________________
        path('questions/', include(([
        path('', question.QuestionListView.as_view(), name='question_change_list'),
        path('question/edit/<int:question_pk>/', question.question_change, name='question_change'),
        #acciones de perguntas crear , guardar , filtrar , borrar
        path('question/add/', question.question_add, name="question_add"),
        path('question/save/<int:question_pk>/', question.question_borrador, name='question_borrador'),
        path('question/save/', question.question_borrador_nueva_pregunta, name='question_borrador_nueva_pregunta'),
        path('question/filter/<str:filter>/', question.question_filter, name='question_filter'),
        path('question/<int:question_pk>/delete/', question.question_delete, name='question_delete'),
    ], 'FundamentosPlay'), namespace='questions')),

    path('teachers/', include(([
        #accion aprobacion/rechazo de preguntas
        path('question/approve/<int:question_pk>/', teachers.question_aprove_view, name='question_approve'),
        path('question/dimiss/<int:question_pk>/', teachers.question_dimiss, name='question_dimiss'),
        #lista de preguntas por aprobar
        path('question/approve/', teachers.QuestionApproveList.as_view(), name="to_approve_list"),
        #lista de estudiantes
        path('mystudents/list', teachers.MyStudentListView.as_view(), name='my_students'),
        #lista de estudiantes por aprobar
        path('students/approve', teachers.StudentToApproveViewList.as_view(), name='students_approve_list'),
        # accion Aprobacion/Rechazo de estudiantes
        path('mystudents/<str:student_username>/approve', teachers.student_approve, name='student_approve'),
        path('mystudents/<str:student_username>/dismiss', teachers.student_dismiss, name='student_dismiss')
    ], 'FundamentosPlay'), namespace='teachers')),


path('administrator/', include(([
        #accion aprobacion/rechazo de preguntas

        path('create_teacher', administrator.create_teacher, name='create_teacher'),
        path('create_assistant', administrator.create_assistant, name='create_assistant'),
        path('users', administrator.UserListView.as_view(), name='user_list'),
        path('questions', administrator.QuestionListView.as_view(), name='question_list'),
        path('question/edit/<int:question_pk>/', administrator.question_change, name='question_change'),
        path('question/<int:question_pk>/delete/', administrator.question_delete, name='question_delete'),





    ], 'FundamentosPlay'), namespace='administrator')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.urls import include, path
from FundamentosPlay.views import home
urlpatterns = [
    path('', include('FundamentosPlay.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # login  es manejado por librerias de django, configuracion de paginas en settings
    path('accounts/signup/', home.SignupView, name='signup'),
]

FundamentosPlay/views/administrator.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import hashlib
import random
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.forms import inlineformset_factory
from django import forms
from FundamentosPlay.models import Question, Answer, User, ProfileAdministration
from FundamentosPlay.views.utils import badges_counter, send_email
from Proyecto import settings
from ..decorators import admin_required, has_permission
from ..forms import TeacherSignUpForm, BaseAnswerInlineFormSet, QuestionForm, QuestionAdminForm, AssistantSignUpForm, \
    RolForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm

@login_required
@admin_required
def create_teacher(request):
    if request.method == 'POST':
        form =TeacherSignUpForm(request.POST)
        if form.is_valid():
            user =form.save()
            #------------------------- Envio de correo  de confirmacion de cuenta-------
            salt = hashlib.sha1( (str(random.random())).encode('utf-8')).hexdigest()[:5]
            activation_key = hashlib.sha1((salt+user.email).encode('utf-8') ).hexdigest()
            key_expires = datetime.datetime.today() + datetime.timedelta(2)
            profileadministration = ProfileAdministration(user=user, activation_key=activation_key,   key_expires=key_expires)
            profileadministration.save()
            email_subject = 'Confirmación de cuenta'
            email_body = "Hola "+user.username+ ", Bienvenido a Fundamentos Play. Para poder jugar y acceder al sistema da clíck en este link en menos de 48 horas: \n" \
                         "http://"+ request.get_host()+"/email_confirm/"+activation_key
            send_email(user.email, email_subject,  email_body)
            #------------------------------------------------------------------
            messages.success(request,'Profesor creado exitosamente, se ha enviado un email de verificación.')
            return redirect('administrator:user_list')
        else:
            form = TeacherSignUpForm(request.POST)
            return render(request, 'FundamentosPlay/administrator/create_teacher.html', {
        'form': form,

    })

    # accion get para presentacion de formulario de registro estudiantes
    else:
        form = TeacherSignUpForm()
        return render(request, 'FundamentosPlay/administrator/create_teacher.html',
                      {"form": form})


@login_required
@admin_required
def create_assistant(request):
    if request.method == 'POST':
        form =AssistantSignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
             #------------------------- Envio de correo  de confirmacion de cuenta-------
            salt = hashlib.sha1( (str(random.random())).encode('utf-8')).hexdigest()[:5]
            activation_key = hashlib.sha1((salt+user.email).encode('utf-8') ).hexdigest()
            key_expires = datetime.datetime.today() + datetime.timedelta(2)
            profileadministration = ProfileAdministration(user=user, activation_key=activation_key,   key_expires=key_expires)
            profileadministration.save()
            email_subject = 'Confirmación de cuenta'
            email_body = "Hola "+user.username+ ", Bienvenido a Fundamentos Play. Para poder jugar y acceder al sistema da clíck en este link en menos de 48 horas: \n" \
                         "http://"+ request.get_host()+"/email_confirm/"+activation_key
            send_email(user.email, email_subject,  email_body)
            #------------------------------------------------------------------
            messages.success(request,'Ayudante creado exitosamente, se ha enviado un email de verificación.')
            return redirect('administrator:user_list')
        else:
            form = AssistantSignUpForm(request.POST)
            return render(request, 'FundamentosPlay/administrator/create_assistant.html', {
        'form': form,

    })

    else:
        form = AssistantSignUpForm()
        return render(request, 'FundamentosPlay/administrator/create_assistant.html',
                      {"form": form})



@method_decorator([login_required, admin_required], name='dispatch')
class UserListView(ListView):
    context_object_name = 'users'
    template_name = 'FundamentosPlay/administrator/user_list.html'
    def get_queryset(self):
        queryset = User.objects.exclude(pk=self.request.user.pk)
        return queryset

    def get_context_data(self, **kwargs):
        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context



#Lista de perguntas totales
@method_decorator([login_required, has_permission], name='dispatch')
class QuestionListView(ListView):

    ordering = ('fecha', )
    context_object_name = 'questions'
    template_name = 'FundamentosPlay/administrator/question_list.html'


    def get_queryset(self):
        queryset = Question.objects.exclude(state="Borrador")
        return queryset



    def get_context_data(self, **kwargs):

        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context





#vista para editar una pregunta
@login_required
@has_permission
def question_change(request,  question_pk):
    question = Question.objects.get(pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        fields=('text', 'is_correct', 'retroalimentacion'),
        formset=BaseAnswerInlineFormSet,
        min_num=2,
        validate_min=True,
        max_num=4,
        validate_max=True,
        widgets={
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            'retroalimentacion': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }
    )
    if request.method == 'POST':
        form = QuestionAdminForm(request.user ,question, request.POST, instance=question)
        formset = AnswerFormSet(request.POST ,instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.state = "Aprobada"
            if len(request.FILES) > 0 and request.FILES['Imagen']:
                myfile = request.FILES['Imagen']
                fs = FileSystemStorage()
                filename = fs.save(str(request.user.username)+str(datetime.date.today())+"."+myfile.name.split(".")[1],myfile)
                question.image = "http://"+request.get_host()+getattr(settings, "MEDIA_URL", None)+filename
            if (formset.is_valid()):
                with transaction.atomic():
                    form.save()
                    formset.save()
                send_email(question.revisor.email, "Pregunta Recibida",
                           question.owner.username + " ha aprobado su pregunta")
                messages.success(request, 'Pregunta aprobada exitosamente!')
                return redirect('administrator:question_list')


        else:
            return render(request, 'FundamentosPlay/administrator/question_list.html', {
                'question': question,
                'form': form,
                'formset': formset,
                'counts': badges_counter(request.user)})
    else:
        form = QuestionAdminForm(request.user, question, instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'FundamentosPlay/administrator/question_edit.html', {
        'question': question,
        'form': form,
        'formset': formset
    })



#borrar una pregunta
@login_required
@has_permission
def question_delete(request,  question_pk):
    if (request.method == 'GET'):
        question = Question.objects.get(pk=question_pk)
        question.delete()
        messages.success(request, 'Pregunta Borrada exitosamente')
        return redirect('administrator:question_list')

FundamentosPlay/views/apiREST.py
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import  Response

from ..models import FichaCompletacion, User, Leaderboard
from ..serializers import FichaSerializer, LeaderBoardSerializer


class Ficha(APIView):

    def get(self,request,username):
        if(request.method == 'GET'):
            fichas = []
            usuario = get_object_or_404(User, username=username)
            queryset = FichaCompletacion.objects.filter(user=usuario)
            for ficha in queryset:
                result = {"nivel": ficha.nivel, "principianteAcertadas": ficha.principianteAcertadas
                    , "principianteFalladas": ficha.principianteFalladas
                    , "intermedioAcertadas": ficha.intermedioAcertadas
                    , "intermedioFalladas": ficha.intermedioAcertadas
                    , "expertoAcertadas": ficha.expertoAcertadas
                    , "expertoFalladas": ficha.expertoAcertadas}
                fichas.append(result)
        serializador = FichaSerializer(fichas, many=True)
        return Response(serializador.data)

    def post(self):
        pass

class Nivel(APIView):

    def get(self,request,username):
        if(request.method == 'GET'):

            usuario = get_object_or_404(User, username=username)
            return Response(usuario.maximo_nivel)


class LeaderBoard(APIView):

    def get(self,request):
        querySet = Leaderboard.objects.all()

        serializador = LeaderBoardSerializer(querySet, many=True)
        return Response(serializador.data)

    def post(self):
        pass

FundamentosPlay/views/assistant.py
from django.contrib.auth import login
from django.shortcuts import  redirect
from django.views.generic import (CreateView)
from ..forms import  AssistantSignUpForm
from ..models import  User



#Registro de Ayudantes
class AssistantSignUpView(CreateView):
    model = User
    form_class =AssistantSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Ayudante'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('questions:question_change_list')

FundamentosPlay/views/students.py
from django.contrib import messages
from django.shortcuts import redirect, render
from ..forms import  StudentSignUpForm
from ..models import User

FundamentosPlay/views/utils.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import hashlib
import random
from django.contrib.sessions.models import Session
from django.core.mail import send_mail
from django.template.backends import django
from django.utils import timezone


from ..models import Question, User, ProfileAdministration


#metodo para obtener los numeros de badges
def badges_counter(user):
    if(user.is_admin):  #si es admin no se le envia numeros en los badges
        enviadas = Question.objects.filter(state="Por Aprobar").count()
        aprobadas = Question.objects.filter(state="Aprobada").count()
        borrador = Question.objects.filter( state="Borrador").count()
        porCorregir = Question.objects.filter( state = "Por Corregir").count()
        return {"PA":enviadas , "AP":aprobadas, "BD":borrador, "PC":porCorregir}
    else:
        enviadas = Question.objects.filter(owner=user,state="Por Aprobar").count()
        aprobadas = Question.objects.filter(owner=user,state="Aprobada").count()
        borrador = Question.objects.filter(owner=user, state="Borrador").count()
        porCorregir = Question.objects.filter(owner=user, state = "Por Corregir").count()
        usuariosPA=   User.objects.filter(profesor=user , is_active=False).count()
        questionsPA = Question.objects.filter(revisor=user , state = "Por Aprobar").count()
        return {"PA":enviadas , "AP":aprobadas, "BD":borrador, "PC":porCorregir, "usersPA":usuariosPA, "questionsPA":questionsPA}


def send_email(para,asunto,mensaje):
    send_mail(
         asunto,
         mensaje,
        'fundamentosplaygame@gmail.com',
        [para],
        fail_silently=False,
    )




def getTipo(user):
    if (user.is_admin):
        tipo = "FundamentosPlay/administrator/administrator.html"
    elif (user.is_teacher):
        tipo = "FundamentosPlay/teachers/teacher.html"
    elif(user.is_student):
        tipo = "FundamentosPlay/students/student.html"
    else:
        tipo = "FundamentosPlay/assistants/assistant.html"
    return tipo

FundamentosPlay/templates/FundamentosPlay/teachers/my_students.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}
{% load static %}

<!-- Scripts -->
{% block scripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>
<script src="{% static 'js/datatables.js' %}"></script>
{% endblock %}


{% block content %}
<h2 class="mb-3">Mis Estudiantes</h2>

    <div class="card">
        <div class="table-responsive">
            <table id="table" class="table mb-0 display">
                <thead  class="thead thead-light">
                    <tr>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                    </tr>
                </thead>
                <tbody>
                  {% for student in students %}
                  <tr>

                      <td class="align-middle"><a href="{% url 'profile' student.username %}">{{ student.username }}</a></td>
                      <td class="align-middle">{{ student.first_name}}</td>
                      <td class="align-middle">{{ student.last_name }}</td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td class="bg-light text-center font-italic" colspan="5">No tiene estudiantes.</td>
                    </tr>
                  {% endfor %}
                </tbody>
          </table>
        </div>


    </div>


{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/question_to_approve_list.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}
{% load static %}


<!-- Scripts -->
{% block scripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>
<script src="{% static 'js/datatables.js' %}"></script>
{% endblock %}



{% block content %}

  <h2 class="mb-3">Preguntas Por Aprobar</h2>

  <div class="card">
    <table id="table" class="table mb-0 display">
      <thead>
        <tr>
          <th>Contenido</th>
          <th>Nivel</th>
          <th>Dificultad</th>
          <th>Fecha</th>
          <th>Creador</th>
        </tr>
      </thead>
      <tbody>
        {% for question in to_approve %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:question_approve' question.pk %}">{{ question}}</a></td>
            <td class="align-middle">{{ question.level}}</td>
            <td class="align-middle">{{ question.Dificultad }}</td>
            <td class="align-middle">{{ question.fecha}}</td>
            <td class="align-middle">{{ question.owner }}</td>

          </tr>
        {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="12">No tiene preguntas por aprobar.</td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/student_approve_list.html
{% extends 'FundamentosPlay/teachers/teacher.html' %}
{% load static %}


<!-- Scripts -->
{% block scripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>
<script src="{% static 'js/datatables.js' %}"></script>
{% endblock %}




{% block content %}

<h2 class="mb-3">Estudiantes por Aprobar</h2>

<div class="card table-responsive">
  <table id="table" class="table mb-0 display">
    <thead>
      <tr>
        <th>Usuario</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td class="align-middle">{{ student }}</td>
          <td class="align-middle">{{ student.first_name}}</td>
          <td class="align-middle">{{ student.last_name }}</td>
          <td class="text-right">
              <a onclick="showLoading()"  href="{% url 'teachers:student_approve' student.username %}" class="btn "><span class="glyphicon glyphicon-ok"></span></a>
              <a  onclick="showLoading()" href="{% url 'teachers:student_dismiss' student.username %}" class="btn ">❌</a>
          </td>

        </tr>
      {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="12">No tiene estudiantes por aprobar .</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

FundamentosPlay/templates/FundamentosPlay/teachers/teacher.html
{% extends 'FundamentosPlay/base_account.html' %}
{% load static %}


<!-- Scripts -->
{% block scripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/profesor.js' %}"></script>
{% endblock %}

{% block dropdown %}
<ul class="nav navbar-nav navbar-right nav-var-username">
    <li class="dropdown">
      <a href="#" id="dropdown_username" class="dropdown-toggle" data-toggle="dropdown">{{user.username}}<span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
          <li><a href="{% url 'profile' user.username %}">Perfil</a></li>
          <li><a href="{% url 'salir' %}">Cerrar Sesión</a></li>
      </ul>
    </li>
</ul>

{% endblock %}


<!----- Menu----->
{% block menu %}
<aside>
    <nav class="navbar    col-sm-3 ">
        <section class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </section>
        <section class="collapse navbar-collapse" id="myNavbar">
             <ul class="nav  navbar-nav navbar-vertical-align ">
                <li class="lititle active col-sm-12"><a href="#"><span class="glyphicon glyphicon-list-alt"></span>  Preguntas</a></li>
                <li class="col-sm-12"><a href="{% url 'questions:question_change_list' %}" class="menu-option"><span class="glyphicon glyphicon-list-alt"></span > Mis Preguntas</a></li>
                <li class="col-sm-12"><a href="{% url 'questions:question_filter' 'Borrador' %}" class="menu-option"><span class="glyphicon glyphicon-inbox"></span> Borrador</a></li>
                <li class="col-sm-12"><a href="{% url 'questions:question_add' %}" class="menu-option"><span class="glyphicon glyphicon-plus"></span>  Crear Pregunta </a></li>
                <li class="col-sm-12"><a href="{% url 'questions:question_filter' 'Por Corregir' %}" class="menu-option"><span class="glyphicon glyphicon-pencil"></span>  Corregir Preguntas <span class="badge">{{counts.PC}}</span></a></li>
                <li class="col-sm-12"><a href="{% url 'teachers:to_approve_list' %}" class="menu-option"><span class="glyphicon glyphicon-ok"></span> Aprobar Preguntas<span class="badge">{{counts.questionsPA}}</span></a></li>

            </ul>

            <ul class="nav navbar-nav navbar-vertical-align">
                <li class="lititle active col-sm-12" ><a href="#"><span class="glyphicon glyphicon-user"></span>  Estudiantes</a></li>
                <li class="col-sm-12"><a href="{% url 'teachers:my_students' %}" class="menu-option"><span class="glyphicon glyphicon-user"></span>  Mis Estudiantes</a></li>
                <li class="col-sm-12"><a href="{% url 'teachers:students_approve_list' %}" class="menu-option"><span class="glyphicon glyphicon-ok"></span>  Aprobar Estudiantes<span class="badge">{{counts.usersPA}}</span></a></li>
            </ul>
           <!---
            <ul class="nav navbar-nav navbar-vertical-align">
                <li class=" lititle active col-sm-12"><a href="#"><span class="glyphicon glyphicon-stats"></span>  Estadísitcas</a></li>
                <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Mis Estadísticas</a></li>
                <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Estadísticas de Estudiantes</a></li>
                <li class="col-sm-12"><a href="#" class="menu-option"><span class="glyphicon glyphicon-stats"></span>  Estadísticas de Niveles</a></li>
            </ul>
            --->
        </section>
    </nav>
</aside>

{% endblock %}


<!-- contenido---->
{% block content %}
{% endblock %}