FundamentosPlay/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from Proyecto import settings
from .views import apiREST
from .views import home,teachers, question, administrator




urlpatterns = [

    path('', home.home, name='home'),
    path('admin/', admin.site.urls),
    path('profile/<str:username>/', home.view_profile, name='profile'),
    path('user/<int:user_pk>/rol/' ,home.edit_rol, name='edit_rol'),
    path('user/<str:user_username>/', home.edit_user_password, name='edit_user_password'),
    path('user/<int:user_pk>/delete/', home.user_delete, name='user_delete'),
    path('user/<int:user_pk>/active/', home.user_active, name='user_active'),
    path('email_confirm/<str:activation_key>/', home.email_confirm, name='email_confirm'),
    path('logout', home.logout, name='salir'),
    path('descarga', home.descarga, name='descarga'),
    path('leaderboard', home.leaderboard, name='leaderboard'),
    path('contactanos', home.sendMail, name='sendMail'),

   #__________________________________ URL PARA API REST _____________________________-
    path('api/', include(([
        #url de servicios
        path('medallas/<str:username>/', apiREST.Ficha.as_view()),
        path('nivel/<str:username>/', apiREST.Nivel.as_view()),
        path('leaderboard/', apiREST.LeaderBoard.as_view(), name='leaderboard'),
    ], 'FundamentosPlay'), namespace='api')),

   #______________________________  URLS PARA  ADMINISTRACIÓN ________________________
        path('questions/', include(([
        path('', question.QuestionListView.as_view(), name='question_change_list'),
        path('question/edit/<int:question_pk>/', question.question_change, name='question_change'),
        #acciones de perguntas crear , guardar , filtrar , borrar
        path('question/add/', question.question_add, name="question_add"),
        path('question/save/<int:question_pk>/', question.question_borrador, name='question_borrador'),
        path('question/save/', question.question_borrador_nueva_pregunta, name='question_borrador_nueva_pregunta'),
        path('question/filter/<str:filter>/', question.question_filter, name='question_filter'),
        path('question/<int:question_pk>/delete/', question.question_delete, name='question_delete'),
    ], 'FundamentosPlay'), namespace='questions')),

    path('teachers/', include(([
        #accion aprobacion/rechazo de preguntas
        path('question/approve/<int:question_pk>/', teachers.question_aprove_view, name='question_approve'),
        path('question/dimiss/<int:question_pk>/', teachers.question_dimiss, name='question_dimiss'),
        #lista de preguntas por aprobar
        path('question/approve/', teachers.QuestionApproveList.as_view(), name="to_approve_list"),
        #lista de estudiantes
        path('mystudents/list', teachers.MyStudentListView.as_view(), name='my_students'),
        #lista de estudiantes por aprobar
        path('students/approve', teachers.StudentToApproveViewList.as_view(), name='students_approve_list'),
        # accion Aprobacion/Rechazo de estudiantes
        path('mystudents/<str:student_username>/approve', teachers.student_approve, name='student_approve'),
        path('mystudents/<str:student_username>/dismiss', teachers.student_dismiss, name='student_dismiss')
    ], 'FundamentosPlay'), namespace='teachers')),


path('administrator/', include(([
        #accion aprobacion/rechazo de preguntas

        path('create_teacher', administrator.create_teacher, name='create_teacher'),
        path('create_assistant', administrator.create_assistant, name='create_assistant'),
        path('users', administrator.UserListView.as_view(), name='user_list'),
        path('questions', administrator.QuestionListView.as_view(), name='question_list'),
        path('question/edit/<int:question_pk>/', administrator.question_change, name='question_change'),
        path('question/<int:question_pk>/delete/', administrator.question_delete, name='question_delete'),





    ], 'FundamentosPlay'), namespace='administrator')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.urls import include, path
from FundamentosPlay.views import home
urlpatterns = [
    path('', include('FundamentosPlay.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # login  es manejado por librerias de django, configuracion de paginas en settings
    path('accounts/signup/', home.SignupView, name='signup'),
]

FundamentosPlay/views/administrator.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import hashlib
import random
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.forms import inlineformset_factory
from django import forms
from FundamentosPlay.models import Question, Answer, User, ProfileAdministration
from FundamentosPlay.views.utils import badges_counter, send_email
from Proyecto import settings
from ..decorators import admin_required, has_permission
from ..forms import TeacherSignUpForm, BaseAnswerInlineFormSet, QuestionForm, QuestionAdminForm, AssistantSignUpForm, \
    RolForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm

@login_required
@admin_required
def create_teacher(request):
    if request.method == 'POST':
        form =TeacherSignUpForm(request.POST)
        if form.is_valid():
            user =form.save()
            #------------------------- Envio de correo  de confirmacion de cuenta-------
            salt = hashlib.sha1( (str(random.random())).encode('utf-8')).hexdigest()[:5]
            activation_key = hashlib.sha1((salt+user.email).encode('utf-8') ).hexdigest()
            key_expires = datetime.datetime.today() + datetime.timedelta(2)
            profileadministration = ProfileAdministration(user=user, activation_key=activation_key,   key_expires=key_expires)
            profileadministration.save()
            email_subject = 'Confirmación de cuenta'
            email_body = "Hola "+user.username+ ", Bienvenido a Fundamentos Play. Para poder jugar y acceder al sistema da clíck en este link en menos de 48 horas: \n" \
                         "http://"+ request.get_host()+"/email_confirm/"+activation_key
            send_email(user.email, email_subject,  email_body)
            #------------------------------------------------------------------
            messages.success(request,'Profesor creado exitosamente, se ha enviado un email de verificación.')
            return redirect('administrator:user_list')
        else:
            form = TeacherSignUpForm(request.POST)
            return render(request, 'FundamentosPlay/administrator/create_teacher.html', {
        'form': form,

    })

    # accion get para presentacion de formulario de registro estudiantes
    else:
        form = TeacherSignUpForm()
        return render(request, 'FundamentosPlay/administrator/create_teacher.html',
                      {"form": form})


@login_required
@admin_required
def create_assistant(request):
    if request.method == 'POST':
        form =AssistantSignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
             #------------------------- Envio de correo  de confirmacion de cuenta-------
            salt = hashlib.sha1( (str(random.random())).encode('utf-8')).hexdigest()[:5]
            activation_key = hashlib.sha1((salt+user.email).encode('utf-8') ).hexdigest()
            key_expires = datetime.datetime.today() + datetime.timedelta(2)
            profileadministration = ProfileAdministration(user=user, activation_key=activation_key,   key_expires=key_expires)
            profileadministration.save()
            email_subject = 'Confirmación de cuenta'
            email_body = "Hola "+user.username+ ", Bienvenido a Fundamentos Play. Para poder jugar y acceder al sistema da clíck en este link en menos de 48 horas: \n" \
                         "http://"+ request.get_host()+"/email_confirm/"+activation_key
            send_email(user.email, email_subject,  email_body)
            #------------------------------------------------------------------
            messages.success(request,'Ayudante creado exitosamente, se ha enviado un email de verificación.')
            return redirect('administrator:user_list')
        else:
            form = AssistantSignUpForm(request.POST)
            return render(request, 'FundamentosPlay/administrator/create_assistant.html', {
        'form': form,

    })

    else:
        form = AssistantSignUpForm()
        return render(request, 'FundamentosPlay/administrator/create_assistant.html',
                      {"form": form})



@method_decorator([login_required, admin_required], name='dispatch')
class UserListView(ListView):
    context_object_name = 'users'
    template_name = 'FundamentosPlay/administrator/user_list.html'
    def get_queryset(self):
        queryset = User.objects.exclude(pk=self.request.user.pk)
        return queryset

    def get_context_data(self, **kwargs):
        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context



#Lista de perguntas totales
@method_decorator([login_required, has_permission], name='dispatch')
class QuestionListView(ListView):

    ordering = ('fecha', )
    context_object_name = 'questions'
    template_name = 'FundamentosPlay/administrator/question_list.html'


    def get_queryset(self):
        queryset = Question.objects.exclude(state="Borrador")
        return queryset



    def get_context_data(self, **kwargs):

        extra_context ={"counts": badges_counter(self.request.user)}
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context





#vista para editar una pregunta
@login_required
@has_permission
def question_change(request,  question_pk):
    question = Question.objects.get(pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        fields=('text', 'is_correct', 'retroalimentacion'),
        formset=BaseAnswerInlineFormSet,
        min_num=2,
        validate_min=True,
        max_num=4,
        validate_max=True,
        widgets={
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            'retroalimentacion': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
        }
    )
    if request.method == 'POST':
        form = QuestionAdminForm(request.user ,question, request.POST, instance=question)
        formset = AnswerFormSet(request.POST ,instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.state = "Aprobada"
            if len(request.FILES) > 0 and request.FILES['Imagen']:
                myfile = request.FILES['Imagen']
                fs = FileSystemStorage()
                filename = fs.save(str(request.user.username)+str(datetime.date.today())+"."+myfile.name.split(".")[1],myfile)
                question.image = "http://"+request.get_host()+getattr(settings, "MEDIA_URL", None)+filename
            if (formset.is_valid()):
                with transaction.atomic():
                    form.save()
                    formset.save()
                send_email(question.revisor.email, "Pregunta Recibida",
                           question.owner.username + " ha aprobado su pregunta")
                messages.success(request, 'Pregunta aprobada exitosamente!')
                return redirect('administrator:question_list')


        else:
            return render(request, 'FundamentosPlay/administrator/question_list.html', {
                'question': question,
                'form': form,
                'formset': formset,
                'counts': badges_counter(request.user)})
    else:
        form = QuestionAdminForm(request.user, question, instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'FundamentosPlay/administrator/question_edit.html', {
        'question': question,
        'form': form,
        'formset': formset
    })



#borrar una pregunta
@login_required
@has_permission
def question_delete(request,  question_pk):
    if (request.method == 'GET'):
        question = Question.objects.get(pk=question_pk)
        question.delete()
        messages.success(request, 'Pregunta Borrada exitosamente')
        return redirect('administrator:question_list')

FundamentosPlay/views/apiREST.py
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import  Response

from ..models import FichaCompletacion, User, Leaderboard
from ..serializers import FichaSerializer, LeaderBoardSerializer


class Ficha(APIView):

    def get(self,request,username):
        if(request.method == 'GET'):
            fichas = []
            usuario = get_object_or_404(User, username=username)
            queryset = FichaCompletacion.objects.filter(user=usuario)
            for ficha in queryset:
                result = {"nivel": ficha.nivel, "principianteAcertadas": ficha.principianteAcertadas
                    , "principianteFalladas": ficha.principianteFalladas
                    , "intermedioAcertadas": ficha.intermedioAcertadas
                    , "intermedioFalladas": ficha.intermedioAcertadas
                    , "expertoAcertadas": ficha.expertoAcertadas
                    , "expertoFalladas": ficha.expertoAcertadas}
                fichas.append(result)
        serializador = FichaSerializer(fichas, many=True)
        return Response(serializador.data)

    def post(self):
        pass

class Nivel(APIView):

    def get(self,request,username):
        if(request.method == 'GET'):

            usuario = get_object_or_404(User, username=username)
            return Response(usuario.maximo_nivel)


class LeaderBoard(APIView):

    def get(self,request):
        querySet = Leaderboard.objects.all()

        serializador = LeaderBoardSerializer(querySet, many=True)
        return Response(serializador.data)

    def post(self):
        pass

FundamentosPlay/views/assistant.py
from django.contrib.auth import login
from django.shortcuts import  redirect
from django.views.generic import (CreateView)
from ..forms import  AssistantSignUpForm
from ..models import  User



#Registro de Ayudantes
class AssistantSignUpView(CreateView):
    model = User
    form_class =AssistantSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Ayudante'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('questions:question_change_list')

FundamentosPlay/views/students.py
from django.contrib import messages
from django.shortcuts import redirect, render
from ..forms import  StudentSignUpForm
from ..models import User

FundamentosPlay/views/utils.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import hashlib
import random
from django.contrib.sessions.models import Session
from django.core.mail import send_mail
from django.template.backends import django
from django.utils import timezone


from ..models import Question, User, ProfileAdministration


#metodo para obtener los numeros de badges
def badges_counter(user):
    if(user.is_admin):  #si es admin no se le envia numeros en los badges
        enviadas = Question.objects.filter(state="Por Aprobar").count()
        aprobadas = Question.objects.filter(state="Aprobada").count()
        borrador = Question.objects.filter( state="Borrador").count()
        porCorregir = Question.objects.filter( state = "Por Corregir").count()
        return {"PA":enviadas , "AP":aprobadas, "BD":borrador, "PC":porCorregir}
    else:
        enviadas = Question.objects.filter(owner=user,state="Por Aprobar").count()
        aprobadas = Question.objects.filter(owner=user,state="Aprobada").count()
        borrador = Question.objects.filter(owner=user, state="Borrador").count()
        porCorregir = Question.objects.filter(owner=user, state = "Por Corregir").count()
        usuariosPA=   User.objects.filter(profesor=user , is_active=False).count()
        questionsPA = Question.objects.filter(revisor=user , state = "Por Aprobar").count()
        return {"PA":enviadas , "AP":aprobadas, "BD":borrador, "PC":porCorregir, "usersPA":usuariosPA, "questionsPA":questionsPA}


def send_email(para,asunto,mensaje):
    send_mail(
         asunto,
         mensaje,
        'fundamentosplaygame@gmail.com',
        [para],
        fail_silently=False,
    )




def getTipo(user):
    if (user.is_admin):
        tipo = "FundamentosPlay/administrator/administrator.html"
    elif (user.is_teacher):
        tipo = "FundamentosPlay/teachers/teacher.html"
    elif(user.is_student):
        tipo = "FundamentosPlay/students/student.html"
    else:
        tipo = "FundamentosPlay/assistants/assistant.html"
    return tipo

FundamentosPlay/templates/FundamentosPlay/administrator/administrator.html
{% extends 'FundamentosPlay/base_account.html' %}
{% load static %}


<!-- Scripts -->
{% block scripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/profesor.js' %}"></script>
{% endblock %}

{% block dropdown %}
<ul class="nav navbar-nav navbar-right nav-var-username">
    <li class="dropdown">
      <a href="#" id="dropdown_username" class="dropdown-toggle" data-toggle="dropdown">{{user.username}}<span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
          <li><a href="{% url 'profile' user.username %}">Perfil</a></li>
          <li><a href="{% url 'salir' %}">Cerrar Sesión</a></li>
      </ul>
    </li>
</ul>
{% endblock %}


<!----- Menu----->
{% block menu %}
<aside>
    <nav class="navbar    col-sm-3 ">
        <section class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </section>
        <section class="collapse navbar-collapse" id="myNavbar">


            <ul class="nav navbar-nav navbar-vertical-align">
                <li class="lititle active col-sm-12" ><a href="#"><span class="glyphicon glyphicon-user"></span>  Usuarios</a></li>
                <li class="col-sm-12"><a href="{% url 'administrator:user_list' %}" class="menu-option"><span class="glyphicon glyphicon-list-alt"></span > Lista de Usuarios</a></li>
                <li class="col-sm-12"><a href="{% url 'administrator:create_teacher' %}" class="menu-option"><span class="glyphicon glyphicon-user"></span>  Crear Profesor</a></li>
                <li class="col-sm-12"><a href="{% url 'administrator:create_assistant' %}" class="menu-option"><span class="glyphicon glyphicon-user"></span>  Crear Ayudante</a></li>

            </ul>

            <ul class="nav  navbar-nav navbar-vertical-align ">
                <li class="lititle active col-sm-12"><a href="#"><span class="glyphicon glyphicon-list-alt"></span>  Preguntas</a></li>
                <li class="col-sm-12"><a href="{% url 'administrator:question_list' %}" class="menu-option"><span class="glyphicon glyphicon-list-alt"></span > Lista de Preguntas</a></li>

            </ul>



        </section>
    </nav>
</aside>

{% endblock %}


<!-- contenido---->
{% block content %}
{% endblock %}

FundamentosPlay/templates/FundamentosPlay/administrator/create_assistant.html
{% extends 'FundamentosPlay/administrator/administrator.html' %}
{% load crispy_forms_tags %}

{% block content %}


  <h2 class="mb-3">Crear Ayudante</h2>
  <form method="post" action="{% url 'administrator:create_assistant' %}" id="form">
  {% csrf_token %}
    {{form|crispy}}

     <button type="submit" class="btn btn-primary" style="float: right;">Crear</button>
  </form>



{% endblock %}

FundamentosPlay/templates/FundamentosPlay/administrator/create_teacher.html
{% extends 'FundamentosPlay/administrator/administrator.html' %}
{% load crispy_forms_tags %}

{% block content %}


  <h2 class="mb-3">Crear Profesor</h2>
  <form method="post" action="{% url 'administrator:create_teacher' %}" id="form">
  {% csrf_token %}
    {{form|crispy}}

     <button type="submit" class="btn btn-primary" style="float: right;">Crear</button>
  </form>



{% endblock %}

FundamentosPlay/templates/FundamentosPlay/administrator/question_edit.html
{% extends 'FundamentosPlay/administrator/administrator.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block scripts %}
<script src="{% static 'js/administrator.js' %}"></script>
<script src="{% static 'js/question.js' %}"></script>

{% endblock %}

{% block content %}
   <div class="centered">{{ question.get_html_badge}}</div>
 <form method="post" action="{% url 'administrator:question_change' question.pk %}" id="form" name="question" enctype="multipart/form-data">
  {% csrf_token %}
    {{ formset.management_form }}
       {% if form.observacion  %}
         <div class="row ">
          <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="panel panel-default ">
              <div class="panel-heading clearfix ">
                <i class="icon-calendar"></i>
                <h3 class="panel-title">Observación</h3>
              </div>

              <div class="panel-body danger">
                <div class="row">
                  <div class="col-lg-12 col-sm-12">
                    <div class="form-group">
                       {{ form.observacion|as_crispy_field }}
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
       {% endif %}


    <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="panel panel-default"style="float:right">
        <div class="panel-heading clearfix">
          <i class="icon-calendar"></i>
          <h3 class="panel-title">Información</h3>
        </div>
        <br>
        <div class="col-lg-6 col-sm-6">
              <div class="input-group">
                 <span class="input-group-addon">Nivel</span>
                {{ form.level|as_crispy_field }}
              </div>
        </div>
         <div class="col-lg-6 col-sm-6">
            <div class="input-group">
              <span class="input-group-addon">Tiempo</span>
              {{ form.tiempo|as_crispy_field }}
              <span class="input-group-addon">seg</span>
            </div>
          </div>


        <br><br>
        <div class="panel-body">

          <div class="input-group input-group-sm">
            <span class="input-group-addon">Dificultad</span>
            {{ form.Dificultad|as_crispy_field }}
          </div>


        </div>
         <div class="panel-body">
            <div class="input-group input-group-sm">
              <span class="input-group-addon">Profesor</span>
              {{ form.revisor|as_crispy_field }}
            </div>
          </div>

          <div class="col-lg-6 col-sm-6">
              <div class="input-group">
                 <span class="input-group-addon">Creador</span>
                {{ form.owner|as_crispy_field }}
              </div>
              <br>

        </div>

      </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="panel panel-default">

            <div class="panel-heading clearfix">
                <i class="icon-calendar"></i>
                <h3 class="panel-title">Imagen</h3>

            </div>

            <br>
            <div class="col-lg-6 col-sm-6">
                <div class="input-group">
                  <div class="input-group input-group-sm">
                        {{ form.Imagen |as_crispy_field }}
                  </div>

                </div>
                {% if question.image %}
                <div class="input-group">
                    <span class="input-group-addon">URL</span>
                    <a target="_blank"  href="{{question.image}}">{{question.image}}</a>
                </div>
                {% endif %}
            </div>
            <br>
            {% if question.image %}
            <div class="panel-body">
                <div class="col-lg-6 col-sm-6">
                    <img id="question_image" src="{{question.image}}" >
                </div>
              </div>
            {% endif %}


            <br><br>




        </div>
      </div>    </div>




    <!-- Row start -->
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <i class="icon-calendar"></i>
            <h3 class="panel-title">Contenido</h3>
          </div>

          <div class="panel-body">
            <div class="row">
              <div class="col-lg-12 col-sm-12">
                <div class="form-group">
                   {{ form.text|as_crispy_field }}
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <i class="icon-calendar"></i>
            <h3 class="panel-title">Respuestas</h3>
            <br>
            <span class="help-block">- Recuerde marcar al menos una respuesta correcta.</span>
            <span class="help-block">- Toda respuesta incorrecta debe tener un retroalimentación.</span>
            <img alt="agregar otra respuesta"  title="Agregar otra respuesta" id="add_button" src="http://macalculatrice.fr/images/plus.png" style="; width:3% ; height: 3%; float:right; clear:right;">


          </div>

          <div class="panel-body respuestas_box  ">
            {% for error in formset.non_form_errors %}
              <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
            {% endfor %}
            <div class="row ">
              <div class="col-sm-1  ">
                <div class="input-group ">
                    <span class="input-group-addon">Correcta</span>
                </div>
              </div>
              <div class="col-sm-5  ">
                <div class="input-group ">
                    <span class="input-group-addon">Respuesta</span>
                </div>
              </div>
              <div class="col-sm-5  ">
                <div class="input-group ">
                    <span class="input-group-addon">Retroalimentación</span>
                </div>
              </div>

            </div>
            <br>

            {% for form in formset %}
                  {% if forloop.counter < 3 %}
                    <div class="row row-{{forloop.counter}}">
                        <div class="col-sm-1  ">
                          <div class="input-group centered ">
                              {{ form.is_correct|as_crispy_field }}
                          </div>
                        </div>
                        <div class="col-lg-5 col-sm-5 col-sx-5">
                          <div class="form-group">
                              {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                               {{ form.text|as_crispy_field }}
                          </div>
                        </div>

                        <div class="col-lg-5 col-sm-5 col-sx-5">
                          <div class="form-group">
                              {{ form.retroalimentacion|as_crispy_field }}
                          </div>
                        </div>


                     </div>
                  {% elif forloop.counter >= 3  %}
                       {% if form.instance.pk %}
                          <div class="row row-{{forloop.counter}} ">
                            <div class="col-sm-1  ">
                              <div class="input-group centered ">
                                  {{ form.is_correct|as_crispy_field }}
                              </div>
                            </div>
                            <div class="col-lg-5 col-sm-5 col-sx-5">
                              <div class="form-group">
                                  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                                   {{ form.text|as_crispy_field }}
                              </div>
                            </div>

                            <div class="col-lg-5 col-sm-5 col-sx-5">
                              <div class="form-group">
                                  {{ form.retroalimentacion|as_crispy_field }}
                              </div>
                            </div>
                            <div class="delete_check">
                                {{ form.DELETE }}
                            </div>
                            <img title ={{forloop.counter}} class='col-sm-1 deletebutton' alt='borrar respuesta'  src='https://image.flaticon.com/icons/svg/61/61848.svg' style='width:5% ; height: 5%; display:block; margin:auto;'>

                         </div>

                       {% else %}
                        <div class="row row-{{forloop.counter}} hide">
                          <div class="col-sm-1  ">
                            <div class="input-group  centered">
                                {{ form.is_correct|as_crispy_field }}
                            </div>
                          </div>
                          <div class="col-lg-5 col-sm-5 col-sx-5">
                            <div class="form-group">
                                 {{ form.text|as_crispy_field }}
                            </div>
                          </div>

                          <div class="col-lg-5 col-sm-5 col-sx-5">
                            <div class="form-group">
                                {{ form.retroalimentacion|as_crispy_field }}
                            </div>
                          </div>

                            <div class="delete_check">
                                {{ form.DELETE }}
                            </div>
                          <img title ={{forloop.counter}} class='col-sm-1 deletebutton' alt='borrar respuesta'  src='https://image.flaticon.com/icons/svg/61/61848.svg' style='width:5% ; height: 5%; display:block; margin:auto;'>

                       </div>

                      {% endif %}
                  {% endif %}
            {% endfor %}



          </div>



        </div>


      </div>

    </div>
    <a href="{% url 'administrator:question_delete' question.id %}" class="btn btn-danger float-left">Borrar</a>
    <button type="submit" class="btn btn-success" style="float: right;">Aprobar</button>




  </form>



{% endblock %}